---
- name: Set to manual selection strategy
  lineinfile:
    path: "{{ cantaloupe_properties_path }}/cantaloupe.properties"
    regexp: '^processor.selection_strategy'
    line: processor.selection_strategy = ManualSelectionStrategy

- name: Copy kakadu libs
  command: cp -r {{ cantaloupe_symlink }}/deps/Linux-x86-64/lib/. /usr/lib64/
  args:
    creates: /usr/lib64/libkdu_a7AR.so

- name: Ensure permissions of kakadu libraries are correct
  file:
    path: "{{ item }}"
    state: file
    owner: root
    group: root
    mode: 0755
  loop:
    - /usr/lib64/libkdu_a7AR.so
    - /usr/lib64/libkdu_jni.so
    - /usr/lib64/libkdu_v7AR.so

- name: Install ImageMagick as fallback processor # Recommended to eliminate warnings about unsupported formats
  yum:
    name: ImageMagick
    state: present
  when: cantaloupe_fallback_processor == "ImageMagickProcessor"

- name: Set fallback processor
  lineinfile:
    path: "{{ cantaloupe_properties_path }}/cantaloupe.properties"
    regexp: '^processor.ManualSelectionStrategy.fallback'
    line: processor.ManualSelectionStrategy.fallback = {{ cantaloupe_fallback_processor }}

# - name: Blank out buggy webp processor
#   lineinfile:
#     path: "{{ cantaloupe_properties_path }}/cantaloupe.properties"
#     regexp: '^processor.ManualSelectionStrategy.webp'
#     line: 'processor.ManualSelectionStrategy.webp = '

- name: Install ffmpeg processor # Eliminates warnings about missing video processor
  block:
    - name: Install repo
      yum:
        name: "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm"
        state: present
    - name: Install packages
      yum:
        name:
          - ffmpeg
          - ffmpeg-devel
        enablerepo:
          - epel
          - nux-desktop
        state: present
  when: cantaloupe_install_ffmpeg | bool
