---

- name: Define General Config changes to make
  set_fact:
    cantaloupe_general_updates:
    - { rexp: '^temp_pathname',
        line: "temp_pathname = {{ cantaloupe_install_root }}/cantaloupe/tmp" }
    - { rexp: '^http.port',
        line: "http.port = {{ cantaloupe_http_port }}" }
    - { rexp: '^endpoint.admin.enabled',
        line: "endpoint.admin.enabled = {{ cantaloupe_is_dev|bool }}" }
    - { rexp: '^endpoint.api.enabled',
        line: "endpoint.api.enabled = {{ cantaloupe_is_dev|bool }}" }
    - { rexp: '^endpoint.admin.secret',
        line: "endpoint.admin.secret = {{ cantaloupe_admin_password }}" }
    - { rexp: '^log.application.level',
        line: "log.application.level = {{ cantaloupe_log_level }}" }
    - { rexp: '^log.application.RollingFileAppender.enabled',
        line: "log.application.RollingFileAppender.enabled = true" }
    - { rexp: '^log.application.RollingFileAppender.pathname',
        line: "log.application.RollingFileAppender.pathname = {{ cantaloupe_log_path }}/application.log" }
    - { rexp: '^log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern',
        line: "log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = {{ cantaloupe_log_path }}/application-%d{yyyy-MM-dd}.log" }
    - { rexp: '^log.error.RollingFileAppender.enabled',
        line: "log.error.RollingFileAppender.enabled = true" }
    - { rexp: '^log.error.RollingFileAppender.pathname',
        line: "log.error.RollingFileAppender.pathname = {{ cantaloupe_log_path }}/error.log" }
    - { rexp: '^log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern',
        line: "log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = {{ cantaloupe_log_path }}/error-%d{yyyy-MM-dd}.log" }

- name: Make General changes
  lineinfile:
    path: "{{ cantaloupe_properties }}"
    regexp: "{{ item.rexp }}"
    line: "{{ item.line }}"
  loop: "{{ cantaloupe_general_updates }}"

