---

- include: java.yml

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Cantaloupe
  include: install.yml

- include: config_general.yml

- include: config_sources.yml

- include: config_processors.yml

- include: service.yml

- name: Ensure cantaloupe service is started
  service:
    name: cantaloupe
    state: started
